---
title: "Relative_CH4Conc_Difference"
author: "Ellery Vaughan"
date: "2025-10-06"
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3$
    toc_float: no
    df_print: kable 
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Relative_CH4Conc_Difference_Analysis 

## Set up 
```{r loading libraries and setting WD}
library(tidyverse)
library(sjPlot)
library(ggtext)
library(emmeans)
library(ggh4x)

setwd("~/Desktop/Berkeley Life/Cal Grad Program/Summer 2024/Cu CH4 Experiment/scripts")
```

# pH Experiment CH4 & CO2 fluxes 

```{r reading in and cleaning data}

# concentration data 
raw1 <- readxl::read_xlsx("../GC_data/calcs/EV_13CH4Inc_CH4_CO2_10.03.25.xlsx", sheet = "final_results")

data1 <- raw1[1:46,1:14]

data1 <- data1 %>%
  mutate(
    # Convert to factors
    soil_type    = factor(recode(soil_type, Control = "Unamended"), 
                          levels = c("Unamended", "Ground Rock")),
    pH_treatment = factor(recode(pH_treatment, 'control' = "Dry control"),
                          levels = c("Dry control", "5", "7", "8")),
    rep          = factor(rep, levels = c("1","2","3","4","5")),
    jar_type     = as.factor(jar_type) ) %>% 
  mutate(CH4_ppm_FINAL = as.numeric(CH4_ppm_FINAL),
         CO2_ppm_INITIAL = as.numeric(CO2_ppm_INITIAL),
         CO2_ppm_FINAL = as.numeric(CO2_ppm_FINAL) )

# timepoint data 
raw2 <- readxl::read_xlsx("../data/13CH4 experiment timepoints.xlsx", sheet = "Sheet1")

data2 <- raw2 %>% 
  select(sample_name,'Incubation Period (Days)','Pre-Incubation Period Total (Days)') %>% 
  rename("T1_inc_time_days" = "Pre-Incubation Period Total (Days)",
         "T2_inc_time_days" = "Incubation Period (Days)") %>% 
  mutate(T1_inc_time_days = as.numeric(T1_inc_time_days),
         T2_inc_time_days = as.numeric(T2_inc_time_days) )

# combining datasets 
data <- left_join(data1,data2)

# adding columns for time normalized concentrations 
data <- data %>% 
  mutate(CH4_ppm_INITIAL = CH4_ppm_INITIAL/T1_inc_time_days,
         CH4_ppm_FINAL = CH4_ppm_FINAL/T2_inc_time_days )

write_csv(data,"conc_change.csv")
  
```

```{r summarizing data}

# Selecting only the experimental jars to include in the figure 
exp_jars <- data %>% 
  filter(jar_type == "Exp")

# Making summarized dataset for mean figures 
summary_exp <- exp_jars %>% 
  group_by(soil_type,pH_treatment) %>% 
  summarize(mean_CH4_ppm_INITIAL = mean(CH4_ppm_INITIAL),
            sd_CH4_ppm_INITIAL = sd(CH4_ppm_INITIAL), 
            n_CH4_ppm_INITIAL = length(CH4_ppm_INITIAL), 
            se_CH4_ppm_INITIAL = sd_CH4_ppm_INITIAL/sqrt(n_CH4_ppm_INITIAL),
            mean_CH4_ppm_FINAL = mean(CH4_ppm_FINAL),
            sd_CH4_ppm_FINAL = sd(CH4_ppm_FINAL),
            n_CH4_ppm_FINAL = length(CH4_ppm_FINAL),
            se_CH4_ppm_FINAL = sd_CH4_ppm_FINAL/sqrt(n_CH4_ppm_FINAL) ) %>% 
  ungroup() %>%
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("Dry control","5","7","8"))
  )

```

```{r TIMEPOINT 1 - time relative CH4 conc differences with dry control}

# p-values to add to figure 
# ANOVA results:
## Unamended soils = p-value: 0.0008897
## Ground rock soils = p-value: 0.4149
CH4_mean_pvals <- data.frame(
  soil_type = c("Unamended", "Ground Rock"),
  x = c(4, 4),  # x-position in each panel
  y = c( max(summary_exp$mean_CH4_ppm_INITIAL*1.25,
         max(summary_exp$mean_CH4_ppm_INITIAL)*1.25) ),  # y-position
  label = c("p < 0.001", "p = 0.41")
) %>% 
  mutate(soil_type = factor(soil_type, levels = c("Unamended","Ground Rock") ) )


# letters for posthoc pairwise results 
CH4_mean_ltrs <- data.frame(
  soil_type   = rep(c("Unamended", "Ground Rock"), each = 4),
  pH_treatment = rep(c("Dry control", "5", "7", "8"), times = 2),
  letters     = c("a", "b", "b", "b",   # panel 1 letters
                  "a", "a", "a", "a"), # panel 2 letters
  mean_CH4_ppm_INITIAL   = summary_exp$mean_CH4_ppm_INITIAL,    # to align letters above bars
  se_CH4_ppm_INITIAL = summary_exp$se_CH4_ppm_INITIAL) %>% 
  mutate(letter_y = case_when(
    pH_treatment %in% c("7", "8") ~ mean_CH4_ppm_INITIAL - se_CH4_ppm_INITIAL - 0.2*max(mean_CH4_ppm_INITIAL), # BELOW error bar
    TRUE ~ mean_CH4_ppm_INITIAL + se_CH4_ppm_INITIAL + 0.2*max(mean_CH4_ppm_INITIAL)                            # ABOVE error bar
  )) %>% 
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("Dry control","5","7","8"))
  )

# CH4 mean figure 
CH4_mean <- ggplot(summary_exp, aes(x=pH_treatment,y=mean_CH4_ppm_INITIAL,fill=pH_treatment) ) +
  geom_col(position = "dodge", color = "black") +
   geom_errorbar(data = summary_exp, aes(x=pH_treatment, ymin=mean_CH4_ppm_INITIAL-se_CH4_ppm_INITIAL, ymax=mean_CH4_ppm_INITIAL+se_CH4_ppm_INITIAL), width=0.25, size=.3) +
  geom_text(data = CH4_mean_ltrs,
            aes(x = pH_treatment, 
                y = letter_y, # bump above error bars
                label = letters),
            inherit.aes = FALSE) +
    geom_label(data = CH4_mean_pvals,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE) +
  facet_wrap2(~soil_type,
             strip = strip_themed(
  background_x = elem_list_rect(fill = rep("gray95", 2)),
  text_x = elem_list_text(color = rep("black", 2)) 
  )) +
  theme_bw () +
  # scale_color_brewer(palette = "Dark2") +
  labs(title = (bquote(Relative~CH[4]~Concentrations~Timepoint1) ),
       x = "pH Treatment",
       y = "CH4 ppm normalized by incubation time (days)") +
  scale_fill_manual(values=c("darkgrey", "#66c2a5", "#fc8d62", "#8da0cb")) +
  scale_color_manual(values=c("darkgrey", "#66c2a5", "#fc8d62", "#8da0cb")) +
  theme(
  plot.title = element_text(size = 20),        # Title text size
  axis.title.x = element_text(size = 14),      # X-axis title text size
  axis.title.y = element_text(size = 14),      # Y-axis title text size
  axis.text.x = element_text(size = 12),       # X-axis text size
  axis.text.y = element_text(size = 12),       # Y-axis text size
  legend.title = element_text(size = 14),      # Legend title text size
  legend.text = element_text(size = 12)        # Legend text size
) +
  labs(fill = "Soil pH Treatment") 

CH4_mean

ggsave(plot = CH4_mean, filename = "../figures/fluxes/10.06.25/CH4_conc_means_NOTNOMRALIZED_T1.png", width = 8.5, height = 5)

```

```{r TIMEPOINT 1 - CH4 stats}

# Unamended soils 
# p-value: 0.0008897
CH4_un_lm <- lm(CH4_ppm_INITIAL ~ pH_treatment, data = subset(exp_jars, soil_type == "Unamended") )
summary(CH4_un_lm)

CH4_un_lm_PW <- emmeans::emmeans(CH4_un_lm, pairwise ~ pH_treatment)
pairs(CH4_un_lm_PW, adjust = "none")

# Ground rock soils 
# p-value: 0.4149
CH4_gr_lm <- lm(CH4_ppm_INITIAL ~ pH_treatment, data = subset(exp_jars, soil_type == "Ground Rock") )
summary(CH4_gr_lm)

CH4_gr_lm_PW <- emmeans::emmeans(CH4_gr_lm, pairwise ~ pH_treatment)
pairs(CH4_gr_lm_PW, adjust = "none")

```

```{r TIMEPOINT 2 - time relative CH4 conc differences with dry control}

# p-values to add to figure 
# ANOVA results:
## Unamended soils = p-value: 0.00542
## Ground rock soils = p-value: 0.01311
CH4_mean_pvals <- data.frame(
  soil_type = c("Unamended", "Ground Rock"),
  x = c(4, 4),  # x-position in each panel
  y = c( max(summary_exp$mean_CH4_ppm_FINAL*1.25,
         max(summary_exp$mean_CH4_ppm_FINAL)*1.25) ),  # y-position
  label = c("p = 0.005", "p = 0.01")
) %>% 
  mutate(soil_type = factor(soil_type, levels = c("Unamended","Ground Rock") ) )


# letters for posthoc pairwise results 
CH4_mean_ltrs <- data.frame(
  soil_type   = rep(c("Unamended", "Ground Rock"), each = 4),
  pH_treatment = rep(c("Dry control", "5", "7", "8"), times = 2),
  letters     = c("a", "a", "b", "b",   # panel 1 letters
                  "a", "a", "b", "ab"), # panel 2 letters
  mean_CH4_ppm_FINAL   = summary_exp$mean_CH4_ppm_FINAL,    # to align letters above bars
  se_CH4_ppm_FINAL = summary_exp$se_CH4_ppm_FINAL) %>% 
  mutate(letter_y = case_when(
    pH_treatment %in% c("7", "8") ~ mean_CH4_ppm_FINAL - se_CH4_ppm_FINAL - 0.2*max(mean_CH4_ppm_FINAL), # BELOW error bar
    TRUE ~ mean_CH4_ppm_FINAL + se_CH4_ppm_FINAL + 0.2*max(mean_CH4_ppm_FINAL)                            # ABOVE error bar
  )) %>% 
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("Dry control","5","7","8"))
  )

# CH4 mean figure 
CH4_mean <- ggplot(summary_exp, aes(x=pH_treatment,y=mean_CH4_ppm_FINAL,fill=pH_treatment) ) +
  geom_col(position = "dodge", color = "black") +
   geom_errorbar(data = summary_exp, aes(x=pH_treatment, ymin=mean_CH4_ppm_FINAL-se_CH4_ppm_FINAL, ymax=mean_CH4_ppm_FINAL+se_CH4_ppm_FINAL), width=0.25, size=.3) +
  geom_text(data = CH4_mean_ltrs,
            aes(x = pH_treatment, 
                y = letter_y, # bump above error bars
                label = letters),
            inherit.aes = FALSE) +
    geom_label(data = CH4_mean_pvals,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE) +
  facet_wrap2(~soil_type,
             strip = strip_themed(
  background_x = elem_list_rect(fill = rep("gray95", 2)),
  text_x = elem_list_text(color = rep("black", 2)) 
  )) +
  theme_bw () +
  # scale_color_brewer(palette = "Dark2") +
  labs(title = (bquote(Relative~CH[4]~Concentrations~TimepoinT2) ),
       x = "pH Treatment",
       y = "CH4 ppm normalized by incubation time (days)") +
  scale_fill_manual(values=c("darkgrey", "#66c2a5", "#fc8d62", "#8da0cb")) +
  scale_color_manual(values=c("darkgrey", "#66c2a5", "#fc8d62", "#8da0cb")) +
  theme(
  plot.title = element_text(size = 20),        # Title text size
  axis.title.x = element_text(size = 14),      # X-axis title text size
  axis.title.y = element_text(size = 14),      # Y-axis title text size
  axis.text.x = element_text(size = 12),       # X-axis text size
  axis.text.y = element_text(size = 12),       # Y-axis text size
  legend.title = element_text(size = 14),      # Legend title text size
  legend.text = element_text(size = 12)        # Legend text size
) +
  labs(fill = "Soil pH Treatment") 

CH4_mean

ggsave(plot = CH4_mean, filename = "../figures/fluxes/10.06.25/CH4_conc_meansT2.png", width = 8.5, height = 5)

```

```{r TIMEPOINT 2 - CH4 stats}

# Unamended soils 
# p-value: 0.00542
CH4_un_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars, soil_type == "Unamended") )
summary(CH4_un_lm)

CH4_un_lm_PW <- emmeans::emmeans(CH4_un_lm, pairwise ~ pH_treatment)
pairs(CH4_un_lm_PW, adjust = "none")

# Ground rock soils 
# p-value: 0.01311
CH4_gr_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars, soil_type == "Ground Rock") )
summary(CH4_gr_lm)

CH4_gr_lm_PW <- emmeans::emmeans(CH4_gr_lm, pairwise ~ pH_treatment)
pairs(CH4_gr_lm_PW, adjust = "none")

```

## WITHOUT DRY CONTROL 

```{r summarizing data}

# Selecting only the experimental jars to include in the figure 
exp_jars2 <- data %>% 
  filter(jar_type == "Exp") %>% 
  filter(pH_treatment != "Dry control")

# Making summarized dataset for mean figures 
summary_exp2 <- exp_jars2 %>% 
  group_by(soil_type,pH_treatment) %>% 
  summarize(mean_CH4_ppm_INITIAL = mean(CH4_ppm_INITIAL),
            sd_CH4_ppm_INITIAL = sd(CH4_ppm_INITIAL), 
            n_CH4_ppm_INITIAL = length(CH4_ppm_INITIAL), 
            se_CH4_ppm_INITIAL = sd_CH4_ppm_INITIAL/sqrt(n_CH4_ppm_INITIAL),
            mean_CH4_ppm_FINAL = mean(CH4_ppm_FINAL),
            sd_CH4_ppm_FINAL = sd(CH4_ppm_FINAL),
            n_CH4_ppm_FINAL = length(CH4_ppm_FINAL),
            se_CH4_ppm_FINAL = sd_CH4_ppm_FINAL/sqrt(n_CH4_ppm_FINAL) ) %>% 
  ungroup() %>%
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("Dry control","5","7","8"))
  )

```

```{r TIMEPOINT 1 - time relative CH4 conc differences with dry control}

# p-values to add to figure 
# ANOVA results:
## Unamended soils = p-value: 0.1793
## Ground rock soils = p-value: 0.1164
CH4_mean_pvals <- data.frame(
  soil_type = c("Unamended", "Ground Rock"),
  x = c(2, 2),  # x-position in each panel
  y = c( max(summary_exp2$mean_CH4_ppm_INITIAL*1.25,
         max(summary_exp2$mean_CH4_ppm_INITIAL)*1.25) ),  # y-position
  label = c("p = 0.18", "p = 0.12")
) %>% 
  mutate(soil_type = factor(soil_type, levels = c("Unamended","Ground Rock") ) )

# letters for posthoc pairwise results 
CH4_mean_ltrs <- data.frame(
  soil_type   = rep(c("Unamended", "Ground Rock"), each = 3),
  pH_treatment = rep(c("5", "7", "8"), times = 2),
  letters     = c("a", "a", "a",   # panel 1 letters
                  "a", "a", "a"), # panel 2 letters
  mean_CH4_ppm_INITIAL   = summary_exp2$mean_CH4_ppm_INITIAL,    # to align letters above bars
  se_CH4_ppm_INITIAL = summary_exp2$se_CH4_ppm_INITIAL) %>% 
  mutate(letter_y = case_when(
    pH_treatment %in% c("7", "8") ~ mean_CH4_ppm_INITIAL - se_CH4_ppm_INITIAL - 0.2*max(mean_CH4_ppm_INITIAL), # BELOW error bar
    TRUE ~ mean_CH4_ppm_INITIAL + se_CH4_ppm_INITIAL + 0.2*max(mean_CH4_ppm_INITIAL)                            # ABOVE error bar
  )) %>% 
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("5","7","8"))
  )

# CH4 mean figure 
CH4_mean <- ggplot(summary_exp2, aes(x=pH_treatment,y=mean_CH4_ppm_INITIAL,fill=pH_treatment) ) +
  geom_col(position = "dodge", color = "black") +
   geom_errorbar(data = summary_exp2, aes(x=pH_treatment, ymin=mean_CH4_ppm_INITIAL-se_CH4_ppm_INITIAL, ymax=mean_CH4_ppm_INITIAL+se_CH4_ppm_INITIAL), width=0.25, size=.3) +
  geom_text(data = CH4_mean_ltrs,
            aes(x = pH_treatment, 
                y = letter_y, # bump above error bars
                label = letters),
            inherit.aes = FALSE) +
    geom_label(data = CH4_mean_pvals,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE) +
  facet_wrap2(~soil_type,
             strip = strip_themed(
  background_x = elem_list_rect(fill = rep("gray95", 2)),
  text_x = elem_list_text(color = rep("black", 2)) 
  )) +
  theme_bw () +
  # scale_color_brewer(palette = "Dark2") +
  labs(title = (bquote(CH[4]~ppm~normalized~by~incubation~duration~days~Timepoint1) ),
       x = "pH Treatment",
       y = "CH4 ppm normalized by incubation time (days)") +
  scale_fill_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  scale_color_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  theme(
  plot.title = element_text(size = 20),        # Title text size
  axis.title.x = element_text(size = 14),      # X-axis title text size
  axis.title.y = element_text(size = 14),      # Y-axis title text size
  axis.text.x = element_text(size = 12),       # X-axis text size
  axis.text.y = element_text(size = 12),       # Y-axis text size
  legend.title = element_text(size = 14),      # Legend title text size
  legend.text = element_text(size = 12)        # Legend text size
) +
  labs(fill = "Soil pH Treatment") 

CH4_mean

ggsave(plot = CH4_mean, filename = "../figures/fluxes/10.06.25/CH4_conc_means_noCONTROL.png", width = 8.5, height = 5)


```

```{r TIMEPOINT 1 - CH4 stats}

# Unamended soils 
# p-value: 0.1793
CH4_un_lm <- lm(CH4_ppm_INITIAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Unamended") )
summary(CH4_un_lm)

CH4_un_lm_PW <- emmeans::emmeans(CH4_un_lm, pairwise ~ pH_treatment)
pairs(CH4_un_lm_PW, adjust = "none")

# Ground rock soils 
# p-value: 0.1164
CH4_gr_lm <- lm(CH4_ppm_INITIAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Ground Rock") )
summary(CH4_gr_lm)

CH4_gr_lm_PW <- emmeans::emmeans(CH4_gr_lm, pairwise ~ pH_treatment)
pairs(CH4_gr_lm_PW, adjust = "none")

```

```{r TIMEPOINT 2 - time relative CH4 conc differences with dry control}

# p-values to add to figure 
# ANOVA results:
## Unamended soils = p-value: 0.1005
## Ground rock soils = p-value: 0.04685
CH4_mean_pvals <- data.frame(
  soil_type = c("Unamended", "Ground Rock"),
  x = c(2, 2),  # x-position in each panel
  y = c( max(summary_exp2$mean_CH4_ppm_FINAL*1.25,
         max(summary_exp2$mean_CH4_ppm_FINAL)*1.25) ),  # y-position
  label = c("p = 0.10", "p = 0.046")
) %>% 
  mutate(soil_type = factor(soil_type, levels = c("Unamended","Ground Rock") ) )

# letters for posthoc pairwise results 
CH4_mean_ltrs <- data.frame(
  soil_type   = rep(c("Unamended", "Ground Rock"), each = 3),
  pH_treatment = rep(c("5", "7", "8"), times = 2),
  letters     = c("a", "a", "a",   # panel 1 letters
                  "a", "a", "a"), # panel 2 letters
  mean_CH4_ppm_FINAL   = summary_exp2$mean_CH4_ppm_FINAL,    # to align letters above bars
  se_CH4_ppm_FINAL = summary_exp2$se_CH4_ppm_FINAL) %>% 
  mutate(letter_y = case_when(
    pH_treatment %in% c("7", "8") ~ mean_CH4_ppm_FINAL - se_CH4_ppm_FINAL - 0.2*max(mean_CH4_ppm_FINAL), # BELOW error bar
    TRUE ~ mean_CH4_ppm_FINAL + se_CH4_ppm_FINAL + 0.2*max(mean_CH4_ppm_FINAL)                            # ABOVE error bar
  )) %>% 
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("5","7","8"))
  )

# CH4 mean figure 
CH4_mean <- ggplot(summary_exp2, aes(x=pH_treatment,y=mean_CH4_ppm_FINAL,fill=pH_treatment) ) +
  geom_col(position = "dodge", color = "black") +
   geom_errorbar(data = summary_exp2, aes(x=pH_treatment, ymin=mean_CH4_ppm_FINAL-se_CH4_ppm_FINAL, ymax=mean_CH4_ppm_FINAL+se_CH4_ppm_FINAL), width=0.25, size=.3) +
  geom_text(data = CH4_mean_ltrs,
            aes(x = pH_treatment, 
                y = letter_y, # bump above error bars
                label = letters),
            inherit.aes = FALSE) +
    geom_label(data = CH4_mean_pvals,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE) +
  facet_wrap2(~soil_type,
             strip = strip_themed(
  background_x = elem_list_rect(fill = rep("gray95", 2)),
  text_x = elem_list_text(color = rep("black", 2)) 
  )) +
  theme_bw () +
  # scale_color_brewer(palette = "Dark2") +
  labs(title = (bquote(CH[4]~ppm~normalized~by~incubation~duration~days~Timepoint2) ),
       x = "pH Treatment",
       y = "CH4 ppm normalized by incubation time (days)") +
  scale_fill_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  scale_color_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  theme(
  plot.title = element_text(size = 20),        # Title text size
  axis.title.x = element_text(size = 14),      # X-axis title text size
  axis.title.y = element_text(size = 14),      # Y-axis title text size
  axis.text.x = element_text(size = 12),       # X-axis text size
  axis.text.y = element_text(size = 12),       # Y-axis text size
  legend.title = element_text(size = 14),      # Legend title text size
  legend.text = element_text(size = 12)        # Legend text size
) +
  labs(fill = "Soil pH Treatment") 

CH4_mean

ggsave(plot = CH4_mean, filename = "../figures/fluxes/10.06.25/CH4_conc_means_T2_noCONTROL.png", width = 8.5, height = 5)


```

```{r TIMEPOINT 2 - CH4 stats}

# Unamended soils 
# p-value: 0.1005
CH4_un_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Unamended") )
summary(CH4_un_lm)

CH4_un_lm_PW <- emmeans::emmeans(CH4_un_lm, pairwise ~ pH_treatment)
pairs(CH4_un_lm_PW, adjust = "none")

# Ground rock soils 
# p-value: 0.04685
CH4_gr_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Ground Rock") )
summary(CH4_gr_lm)

CH4_gr_lm_PW <- emmeans::emmeans(CH4_gr_lm, pairwise ~ pH_treatment)
pairs(CH4_gr_lm_PW, adjust = "none")

```

# just concentration 
```{r TIMEPOINT 2 - time relative CH4 conc differences with dry control}


# Selecting only the experimental jars to include in the figure 
exp_jars2 <- data %>% 
  filter(jar_type == "Exp") %>% 
  filter(pH_treatment != "Dry control")

# Making summarized dataset for mean figures 
summary_exp2 <- exp_jars2 %>% 
  group_by(soil_type,pH_treatment) %>% 
  summarize(mean_CH4_ppm_INITIAL = mean(CH4_ppm_INITIAL),
            sd_CH4_ppm_INITIAL = sd(CH4_ppm_INITIAL), 
            n_CH4_ppm_INITIAL = length(CH4_ppm_INITIAL), 
            se_CH4_ppm_INITIAL = sd_CH4_ppm_INITIAL/sqrt(n_CH4_ppm_INITIAL),
            mean_CH4_ppm_FINAL = mean(CH4_ppm_FINAL),
            sd_CH4_ppm_FINAL = sd(CH4_ppm_FINAL),
            n_CH4_ppm_FINAL = length(CH4_ppm_FINAL),
            se_CH4_ppm_FINAL = sd_CH4_ppm_FINAL/sqrt(n_CH4_ppm_FINAL) ) %>% 
  ungroup() %>%
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("5","7","8"))
  )


# p-values to add to figure 
# ANOVA results:
## Unamended soils = p-value: 0.1005
## Ground rock soils = p-value: 0.04685
CH4_mean_pvals <- data.frame(
  soil_type = c("Unamended", "Ground Rock"),
  x = c(2, 2),  # x-position in each panel
  y = c( max(summary_exp2$mean_CH4_ppm_FINAL*1.25,
         max(summary_exp2$mean_CH4_ppm_FINAL)*1.25) ),  # y-position
  label = c("p = 0.10", "p = 0.046")
) %>% 
  mutate(soil_type = factor(soil_type, levels = c("Unamended","Ground Rock") ) )

# letters for posthoc pairwise results 
CH4_mean_ltrs <- data.frame(
  soil_type   = rep(c("Unamended", "Ground Rock"), each = 3),
  pH_treatment = rep(c("5", "7", "8"), times = 2),
  letters     = c("a", "a", "a",   # panel 1 letters
                  "a", "a", "a"), # panel 2 letters
  mean_CH4_ppm_FINAL   = summary_exp2$mean_CH4_ppm_FINAL,    # to align letters above bars
  se_CH4_ppm_FINAL = summary_exp2$se_CH4_ppm_FINAL) %>% 
  mutate(letter_y = case_when(
    pH_treatment %in% c("7", "8") ~ mean_CH4_ppm_FINAL - se_CH4_ppm_FINAL - 0.2*max(mean_CH4_ppm_FINAL), # BELOW error bar
    TRUE ~ mean_CH4_ppm_FINAL + se_CH4_ppm_FINAL + 0.2*max(mean_CH4_ppm_FINAL)                            # ABOVE error bar
  )) %>% 
  mutate(
    soil_type = factor(soil_type, levels = c("Unamended","Ground Rock")),
    pH_treatment = factor(pH_treatment, levels = c("5","7","8"))
  )

# CH4 mean figure 
CH4_mean <- ggplot(summary_exp2, aes(x=pH_treatment,y=mean_CH4_ppm_FINAL,fill=pH_treatment) ) +
  geom_col(position = "dodge", color = "black") +
   geom_errorbar(data = summary_exp2, aes(x=pH_treatment, ymin=mean_CH4_ppm_FINAL-se_CH4_ppm_FINAL, ymax=mean_CH4_ppm_FINAL+se_CH4_ppm_FINAL), width=0.25, size=.3) +
  geom_text(data = CH4_mean_ltrs,
            aes(x = pH_treatment, 
                y = letter_y, # bump above error bars
                label = letters),
            inherit.aes = FALSE) +
    geom_label(data = CH4_mean_pvals,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE) +
  facet_wrap2(~soil_type,
             strip = strip_themed(
  background_x = elem_list_rect(fill = rep("gray95", 2)),
  text_x = elem_list_text(color = rep("black", 2)) 
  )) +
  theme_bw () +
  # scale_color_brewer(palette = "Dark2") +
  labs(title = (bquote(CH[4]~ppm~normalized~by~incubation~duration~days~Timepoint2) ),
       x = "pH Treatment",
       y = "CH4 ppm normalized by incubation time (days)") +
  scale_fill_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  scale_color_manual(values=c("#66c2a5", "#fc8d62", "#8da0cb")) +
  theme(
  plot.title = element_text(size = 20),        # Title text size
  axis.title.x = element_text(size = 14),      # X-axis title text size
  axis.title.y = element_text(size = 14),      # Y-axis title text size
  axis.text.x = element_text(size = 12),       # X-axis text size
  axis.text.y = element_text(size = 12),       # Y-axis text size
  legend.title = element_text(size = 14),      # Legend title text size
  legend.text = element_text(size = 12)        # Legend text size
) +
  labs(fill = "Soil pH Treatment") 

CH4_mean

ggsave(plot = CH4_mean, filename = "../figures/fluxes/10.06.25/CH4_conc_means_T2_noCONTROL.png", width = 8.5, height = 5)


```

```{r TIMEPOINT 2 - CH4 stats}

# Unamended soils 
# p-value: 0.1005
CH4_un_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Unamended") )
summary(CH4_un_lm)

CH4_un_lm_PW <- emmeans::emmeans(CH4_un_lm, pairwise ~ pH_treatment)
pairs(CH4_un_lm_PW, adjust = "none")

# Ground rock soils 
# p-value: 0.04685
CH4_gr_lm <- lm(CH4_ppm_FINAL ~ pH_treatment, data = subset(exp_jars2, soil_type == "Ground Rock") )
summary(CH4_gr_lm)

CH4_gr_lm_PW <- emmeans::emmeans(CH4_gr_lm, pairwise ~ pH_treatment)
pairs(CH4_gr_lm_PW, adjust = "none")

```


